export const defaultCompetencyCatalog = [
  { code: '', name: 'Einarbeitung', category: 'Allgemein', relevance: 'Alle', note: 'Praktische Einarbeitung im Pflegealltag' },
  { code: 'P01', name: 'Ganzwaschung', category: 'SGB XI', relevance: 'Alle', note: 'Vollständige Körperpflege. Schließt P02 am selben Besuch aus.' },
  { code: 'P02', name: 'Teilwaschung', category: 'SGB XI', relevance: 'Alle', note: 'Nur Teilbereiche (z. B. Gesicht, Hände). Nicht zusammen mit P01 abrechenbar.' },
  { code: 'P03', name: 'Ausscheidungen', category: 'SGB XI', relevance: 'Alle', note: 'Hilfe bei Toilettengang, Inkontinenzversorgung, Katheterpflege. Dokumentation: Art der Ausscheidungshilfe angeben.' },
  { code: 'P04', name: 'Selbstständige Nahrungsaufnahme', category: 'SGB XI', relevance: 'Alle', note: 'Klient isst selbst - MA bereitet nur vor (richten, schneiden). Nicht kombinierbar mit P05.' },
  { code: 'P05', name: 'Hilfe bei der Nahrungsaufnahme', category: 'SGB XI', relevance: 'Alle', note: 'MA reicht aktiv an. Nicht zusammen mit P04. Bei Schluckstörung in Doku vermerken.' },
  { code: 'P06', name: 'Sondenernährung', category: 'SGB XI', relevance: 'Nur PFK', note: 'Nur mit ärztlicher Anordnung. Behandlungspflege unter SGB V mitprüfen.' },
  { code: 'P07', name: 'Lagern / Betten', category: 'SGB XI', relevance: 'Alle', note: 'Positionierung, Bett machen. Bei Kombination mit Grundpflege Kombinations-LK prüfen.' },
  { code: 'P08', name: 'Mobilisation', category: 'SGB XI', relevance: 'Alle', note: 'Transfer, Gehen, Rollstuhl. Bei höherem Aufwand in der Doku begründen.' },
  { code: 'P09', name: 'Behördengänge und Arztbesuche', category: 'SGB XI', relevance: 'Alle', note: 'Begleitung außer Haus. Zeitaufwand dokumentieren.' },
  { code: 'P10', name: 'Beheizen des Wohnbereichs', category: 'SGB XI', relevance: 'Alle', note: 'Nur wenn Klient dies nicht selbst kann. In Doku begründen.' },
  { code: 'P11', name: 'Einkaufen', category: 'SGB XI', relevance: 'Alle', note: 'Belege als Nachweis aufbewahren lassen.' },
  { code: 'P12', name: 'Zubereiten von warmen Mahlzeiten', category: 'SGB XI', relevance: 'Alle', note: 'Nicht kombinierbar mit P04/P05 am selben Besuch, wenn Essen direkt gereicht wird.' },
  { code: 'P13', name: 'Reinigung der Wohnung', category: 'SGB XI', relevance: 'Alle', note: 'Nur pflegerelevante Bereiche. Umfang in Doku angeben.' },
  { code: 'P14', name: 'Waschen und Pflegen der Wäsche / Kleidung', category: 'SGB XI', relevance: 'Alle', note: 'Nur wenn im Pflegevertrag vereinbart.' },
  { code: 'P15', name: 'Hausbesuchspauschale', category: 'SGB XI', relevance: 'Alle', note: 'Einmal pro Besuch - unabhängig von der Anzahl der LK.' },
  { code: 'P15a', name: 'Erhöhte Hausbesuchspauschale', category: 'SGB XI', relevance: 'Alle', note: 'Nur wenn vertraglich vereinbart, z. B. Nacht, Wochenende oder Feiertag.' },
  { code: 'P16', name: 'Erstgespräch', category: 'SGB XI', relevance: 'Nur PFK', note: 'Einmalig bei Neuaufnahme, inklusive Assessment und SIS.' },
  { code: 'P16a', name: 'Folgegespräch', category: 'SGB XI', relevance: 'Nur PFK', note: 'Regelmäßige Überprüfung der Pflegesituation und Übertrag in SIS/Maßnahmenplan.' },
  { code: 'P17', name: 'Beratungsbesuch § 37 Abs. 3 S. 6 SGB XI', category: 'SGB XI', relevance: 'Nur PFK', note: 'Pflicht bei Pflegegeld-Empfängern. Bericht an Pflegekasse.' },
  { code: 'P18', name: 'Große Grundpflege m. Lagern / selbst. Nahrungsaufnahme', category: 'SGB XI', relevance: 'Alle', note: 'Enthält P01 + P07 + P04. Enthaltene Einzel-LK nicht zusätzlich ziehen.' },
  { code: 'P19', name: 'Große Grundpflege', category: 'SGB XI', relevance: 'Alle', note: 'Enthält P01. P07 und P04/P05 nicht zusätzlich.' },
  { code: 'P20', name: 'Kleine Grundpflege m. Lagern / selbst. Nahrungsaufnahme', category: 'SGB XI', relevance: 'Alle', note: 'Enthält P02 + P07 + P04.' },
  { code: 'P21', name: 'Kleine Grundpflege', category: 'SGB XI', relevance: 'Alle', note: 'Enthält P02. P07 und P04/P05 nicht zusätzlich.' },
  { code: 'P22', name: 'Große hauswirtschaftliche Versorgung', category: 'SGB XI', relevance: 'Alle', note: 'Kombination mehrerer hauswirtschaftlicher Leistungen.' },
  { code: 'P23', name: 'Große Grundpflege m. Lagern', category: 'SGB XI', relevance: 'Alle', note: 'Enthält P01 + P07. P04/P05 kann zusätzlich abgerechnet werden.' },
  { code: 'P24', name: 'Große Grundpflege m. Lagern / Hilfe Nahrungsaufnahme', category: 'SGB XI', relevance: 'Alle', note: 'Enthält P01 + P07 + P05.' },
  { code: 'P25', name: 'Kleine Grundpflege m. Lagern', category: 'SGB XI', relevance: 'Alle', note: 'Enthält P02 + P07. P04/P05 kann zusätzlich abgerechnet werden.' },
  { code: 'P26', name: 'Kleine Grundpflege m. Lagern / Hilfe Nahrungsaufnahme', category: 'SGB XI', relevance: 'Alle', note: 'Enthält P02 + P07 + P05.' },
  { code: 'P27', name: 'Kleine pflegerische Hilfestellung 1', category: 'SGB XI', relevance: 'Alle', note: 'Kurzer Einsatz. Nicht zusammen mit P01-P08 oder Kombinations-LK abrechenbar.' },
  { code: 'P28', name: 'Kleine pflegerische Hilfestellung 2', category: 'SGB XI', relevance: 'Alle', note: 'Kurzer Einsatz. Nicht zusammen mit P01-P08 oder Kombinations-LK abrechenbar.' },
  { code: 'P29', name: 'Kleine pflegerische Hilfestellung 3', category: 'SGB XI', relevance: 'Alle', note: 'Kurzer Einsatz. Nicht zusammen mit P01-P08 oder Kombinations-LK abrechenbar.' },
  { code: 'P30', name: 'Kleine pflegerische Hilfestellung 4', category: 'SGB XI', relevance: 'Alle', note: 'Kurzer Einsatz. Nicht zusammen mit P01-P08 oder Kombinations-LK abrechenbar.' },
  { code: 'P31', name: 'Pflegerische Betreuung', category: 'SGB XI', relevance: 'Alle', note: 'Gespräch, Aktivierung, Beschäftigung ohne körperlichen Pflegeakt.' },
  { code: 'P32', name: 'Hilfe bei der Sicherstellung der selbstverantworteten Haushaltsführung', category: 'SGB XI', relevance: 'Alle', note: 'Aktivierend begleiten statt übernehmen.' },
  { code: 'P33', name: 'Hauswirtschaftliche Versorgung', category: 'SGB XI', relevance: 'Alle', note: 'Vollständige hauswirtschaftliche Übernahme. Abgrenzung zu P22 beachten.' },
  { code: 'BPf 1', name: 'Medikamentenvorbereitung (Stellen der Medikamente)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 2', name: 'Medikamentengabe oral / sublingual', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 3', name: 'Medikamentengabe inhalativ (Inhalation)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 4', name: 'Medikamentengabe transdermal (Pflaster)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 5', name: 'Subkutane Injektion (z.B. Insulin, Heparin)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 6', name: 'Intramuskuläre Injektion (nach ärztl. Anordnung)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 7', name: 'Infusionstherapie / Port-Versorgung', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 8', name: 'Ernährung über PEG-Sonde', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 9', name: 'Wundbeurteilung und Dokumentation (TIME-Schema)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 10', name: 'Verbandswechsel (aseptische Technik)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 11', name: 'Wundspülung / Debridement (nach Anordnung)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 12', name: 'Drainageversorgung (Wunddrainage)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 13', name: 'Transurethraler Blasenkatheter legen (Frau)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 14', name: 'Suprapubischer Katheter - Pflege und Wechsel', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 15', name: 'Einlauf / Klysma / Darmentleerung', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 16', name: 'Einmalkatheterisierung', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 17', name: 'Tracheostomapflege (tracheal endtracheale Absaugung)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 18', name: 'Inhalationstherapie (Vernebler, Peak-Flow)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 19', name: 'Absaugung (oral / nasal)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 20', name: 'O2-Therapie (Sauerstoffgabe, Pulsoximetrie)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 21', name: 'Kompressionsverbände anlegen (Kurzzugbinde)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 22', name: 'Kompressionsstrümpfe Klasse I-III anlegen', category: 'SGB V', relevance: 'Alle', note: '' },
  { code: 'BPf 23', name: 'Lymphdrainage-Nachsorge / Entstauungstherapie', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 24', name: 'Vitalzeichenkontrolle + Dokumentation (RR, P, T, SpO2)', category: 'SGB V', relevance: 'Alle', note: '' },
  { code: 'BPf 25', name: 'EKG ableiten (12-Kanal)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 26', name: 'Blutzucker-Messung + Insulin-Protokoll', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 27', name: 'INR/Quick-Messung (CoaguChek)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 28', name: 'Beurteilung und Meldung krit. Vitalwerte', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 29', name: 'Beratung Patient/Angehörige (Pflegeberatung § 37 SGB XI)', category: 'SGB V', relevance: 'Nur PFK', note: '' },
  { code: 'BPf 30', name: 'Demenzbegleitung / Validation', category: 'SGB V', relevance: 'Alle', note: '' },
] as const;

/**
 * Intervals are only set where a norm gives one; see docs/adr/0002 and the
 * research it cites. `intervalMonths: null` means "no fixed interval" and must
 * not be filled in with a plausible-looking number.
 */
export const defaultInstructionCatalog = [
  { topic: 'Erstunterweisung Arbeitsschutz', legalBasis: 'ArbSchG § 12 / DGUV V1 § 4', note: '', intervalMonths: 12, intervalSource: 'norm' },
  { topic: 'Brandschutzunterweisung', legalBasis: 'ArbStättV § 6 / ASR A2.2', note: '', intervalMonths: 12, intervalSource: 'norm' },
  { topic: 'Hygieneunterweisung (jährlich)', legalBasis: 'BioStoffV § 14 / TRBA 250', note: '', intervalMonths: 12, intervalSource: 'norm' },
  { topic: 'MRSA - Standard Umgang & Schutz', legalBasis: 'VA-HYG-003', note: '' },
  { topic: 'Datenschutz-Grundunterweisung', legalBasis: 'DSGVO / BDSG', note: '' },
  { topic: 'Schweigepflicht (§ 203 StGB)', legalBasis: '§ 203 StGB', note: '' },
  { topic: 'Reanimationstraining (BLS/AED)', legalBasis: 'interne Richtlinie', note: '' },
  // Kein Zeitintervall: die MPBetreibV kennt nur produktbezogene Ausloeser.
  { topic: 'Einweisung Medizinprodukte (MPG)', legalBasis: 'MPBetreibV § 4 / § 11', note: '' },
  { topic: 'Notfallmanagement / FAST-Erkennung', legalBasis: 'interne Richtlinie', note: '' },
  { topic: 'Kinästhetik Grundkurs (optional)', legalBasis: 'interne Richtlinie', note: '' },
  { topic: 'Bobath-Grundprinzipien (optional)', legalBasis: 'interne Richtlinie', note: '' },
  { topic: 'Expertenstandard Dekubitus', legalBasis: 'DNQP', note: '' },
  { topic: 'Expertenstandard Sturz', legalBasis: 'DNQP', note: '' },
  { topic: 'Expertenstandard Schmerz', legalBasis: 'DNQP', note: '' },
  { topic: 'Umgang mit Betäubungsmitteln (BTM)', legalBasis: 'BtMG', note: '' },
  { topic: 'Abfallentsorgung nach LAGA', legalBasis: 'KrWG / LAGA', note: '', intervalMonths: 12, intervalSource: 'norm' },
  { topic: 'Tourenplanung & Dienstplanung', legalBasis: 'interne Richtlinie', note: '' },
  { topic: 'SIS-Dokumentation (Strukturmodell)', legalBasis: 'PSG II / BMG', note: '' },
  { topic: 'Pflegegradmanagement & Begutachtung', legalBasis: 'SGB XI § 18', note: '' },
  { topic: 'Abrechnungssystem SGB XI / LK', legalBasis: 'SGB XI', note: '' },

  // Ergaenzt nach der Recherche vom 05.09.2026 (docs/research/unterweisungs-
  // intervalle-ambulante-pflege.md): Pflichten mit belegtem Intervall, die im
  // ursprünglichen Katalog fehlten.
  {
    topic: 'Unterweisung Gefahrstoffe (Desinfektion & Reinigung)',
    legalBasis: 'GefStoffV § 14 Abs. 2',
    note: 'Tätigkeiten mit Desinfektions- und Reinigungsmitteln unterliegen der Gefahrstoffverordnung.',
    intervalMonths: 12,
    intervalSource: 'norm',
  },
  {
    topic: 'Ersthelfer-Fortbildung',
    legalBasis: 'DGUV V1 § 26 Abs. 3',
    note: 'Wer eine abgeschlossene Ausbildung in einem Gesundheitsberuf hat, gilt bei regelmäßiger Erste-Hilfe-Praxis als fortgebildet (§ 26 Abs. 3 S. 3).',
    intervalMonths: 24,
    intervalSource: 'norm',
  },
  {
    topic: 'Brandschutzhelfer-Ausbildung',
    legalBasis: 'ASR A2.2 Abschn. 7.3',
    note: 'Keine Pflichtfrist. Empfohlen werden 2 bis 5 Jahre; verbindlich ist die eigene Gefährdungsbeurteilung.',
  },
  {
    topic: 'Hautschutzunterweisung',
    legalBasis: 'TRBA 250 Abschn. 4.1.3 Abs. 3',
    note: 'Zusätzlich vor der Verwendung neuer Präparate.',
    intervalMonths: 12,
    intervalSource: 'norm',
  },
  {
    topic: 'Belehrung nach IfSG § 43',
    legalBasis: 'IfSG § 43 Abs. 4',
    note: 'Nur bei eigener Küche oder Gemeinschaftsverpflegung. Der private hauswirtschaftliche Bereich ist nach § 42 Abs. 1 S. 3 ausgenommen.',
    intervalMonths: 24,
    intervalSource: 'norm',
  },
] as const;
